## Sentiment Analysis <- Encoder only

In [1]:
import pandas as pd

# modify the column width
pd.set_option('display.max_colwidth', None)

# look at a subset of the movie reviews
data_df = pd.read_csv('../resources/Course Materials/Data/movie_reviews_sentiment.csv')
sentiment_df = \
    data_df[['movie_title', 'movie_info', 'sentiment_vader']] \
        .rename(columns={'movie_title': 'title', 'movie_info': 'info', 'sentiment_vader': 'vader'})
sentiment_df.head()

,title,info,vader
0,A Dog's Journey,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",0.9837
1,A Dog's Way Home,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",0.9237
2,A Tuba to Cuba,"The leader of New Orleans' famed Preservation Hall Jazz Band seeks to fulfill his late father's dream of retracing their musical roots to the shores of Cuba in search of the indigenous music that gave birth to New Orleans jazz. A TUBA TO CUBA celebrates the triumph of the human spirit expressed through the universal language of music and challenges us to resolve to build bridges, not walls.",0.9360
3,A Vigilante,"A once abused woman, Sadie (Olivia Wilde), devotes herself to ridding victims of their domestic abusers while hunting down the husband she must kill to truly be free. A Vigilante is a thriller inspired by the strength and bravery of real domestic abuse survivors and the incredible obstacles to safety they face.",-0.0334
4,After,"Based on Anna Todd's best-selling novel which became a publishing sensation on social storytelling platform Wattpad, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants out of life.",0.9349

In [2]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    # Check available GPU memory
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    torch.cuda.empty_cache()  # Clear cache before starting
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using Apple MPS")
else:
    device = torch.device("cpu")
    print("Using CPU")

Using GPU: NVIDIA GeForce GTX 1650 with Max-Q Design
GPU Memory: 4.29 GB

In [3]:
# sentiment analysis with hugging face
from transformers import pipeline

In [4]:
%%time

# utilize machine's GPU if it has one
sentiment_analyzer = pipeline("sentiment-analysis",
                              model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
                              device=device,
                              truncation=True)

# Use a batch size so that pipelines can run in parallel
sentiment_scores = sentiment_df['info'].apply(sentiment_analyzer, batch_size=8)

if torch.cuda.is_available():
    print(f"Memory used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")
    
sentiment_scores[:5]

Device set to use cuda
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Memory used: 0.28 GB
CPU times: total: 3.08 s
Wall time: 3.98 s

0    [{'label': 'POSITIVE', 'score': 0.9982469081878662}]
1    [{'label': 'POSITIVE', 'score': 0.9995336532592773}]
2    [{'label': 'POSITIVE', 'score': 0.9994434714317322}]
3    [{'label': 'POSITIVE', 'score': 0.9994601607322693}]
4    [{'label': 'POSITIVE', 'score': 0.9972022771835327}]
Name: info, dtype: object

In [5]:
# extract the label and score and create a sentiment score for all reviews
sentiment_df['Label_HF'] = sentiment_scores.apply(lambda x: x[0]['label'])
sentiment_df['Score_HF'] = sentiment_scores.apply(lambda x: x[0]['score'])

# Note: When using 'apply' on a whole dataframe (rather than a series), by default axis=0 which applies lambda to each column
# ...but we want lambda applied to each row -> axis=1
sentiment_df['Sentiment_HF'] = sentiment_df.apply(lambda row: row['Score_HF'] if row['Label_HF'] == 'POSITIVE' else -row['Score_HF'], axis=1)
sentiment_df.head()

,title,info,vader,Label_HF,Score_HF,Sentiment_HF
0,A Dog's Journey,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",0.9837,POSITIVE,0.998247,0.998247
1,A Dog's Way Home,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",0.9237,POSITIVE,0.999534,0.999534
2,A Tuba to Cuba,"The leader of New Orleans' famed Preservation Hall Jazz Band seeks to fulfill his late father's dream of retracing their musical roots to the shores of Cuba in search of the indigenous music that gave birth to New Orleans jazz. A TUBA TO CUBA celebrates the triumph of the human spirit expressed through the universal language of music and challenges us to resolve to build bridges, not walls.",0.9360,POSITIVE,0.999443,0.999443
3,A Vigilante,"A once abused woman, Sadie (Olivia Wilde), devotes herself to ridding victims of their domestic abusers while hunting down the husband she must kill to truly be free. A Vigilante is a thriller inspired by the strength and bravery of real domestic abuse survivors and the incredible obstacles to safety they face.",-0.0334,POSITIVE,0.999460,0.999460
4,After,"Based on Anna Todd's best-selling novel which became a publishing sensation on social storytelling platform Wattpad, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants out of life.",0.9349,POSITIVE,0.997202,0.997202

In [6]:
sentiment_df.sort_values('Sentiment_HF').head()

,title,info,vader,Label_HF,Score_HF,Sentiment_HF
22,Braid,"Two wanted women decide to rob their wealthy yet mentally unstable friend who lives in a fantasy world they all created as children. To take her money, the girls must take part in a deadly and perverse game of make believe throughout a sprawling yet decaying estate. As things become increasingly violent and hallucinatory, they realize that obtaining the money may be the least of their concerns.",-0.8316,NEGATIVE,0.999203,-0.999203
103,Spider-Man: Far From Home,"Peter Parker returns in Spider-Man: Far From Home, the next chapter of the Spider-Man: Homecoming series! Our friendly neighborhood Super Hero decides to join his best friends Ned, MJ, and the rest of the gang on a European vacation. However, Peter's plan to leave super heroics behind for a few weeks are quickly scrapped when he begrudgingly agrees to help Nick Fury uncover the mystery of several elemental creature attacks, creating havoc across the continent!",0.9722,NEGATIVE,0.998805,-0.998805
34,Dragged Across Concrete,"DRAGGED ACROSS CONCRETE follows two police detectives who find themselves suspended when a video of their strong-arm tactics is leaked to the media. With little money and no options, the embittered policemen descend into the criminal underworld and find more than they wanted waiting in the shadows.",-0.9015,NEGATIVE,0.998734,-0.998734
165,Yesterday,"Jack Malik (Himesh Patel, BBC's Eastenders) is a struggling singer-songwriter in a tiny English seaside town whose dreams of fame are rapidly fading, despite the fierce devotion and support of his childhood best friend, Ellie (Lily James, Mamma Mia! Here We Go Again). Then, after a freak bus accident during a mysterious global blackout, Jack wakes up to discover that The Beatles have never existed... and he finds himself with a very complicated problem, indeed.",0.1365,NEGATIVE,0.998447,-0.998447
102,Skin,"A white supremacist reforms his life after falling in love but saying goodbye to his skinhead life isn't a clean process. He must betray his former gang and work alongside the FBI in order to remove the body ink that has represented his identity for so long, as well as the burden of the gang's crimes he has carried.",-0.8377,NEGATIVE,0.996846,-0.996846

## Named Entity Recognition (NER) <- Encoder only

In [7]:
import pandas as pd

book_df = pd.read_csv('../resources/Course Materials/Data/childrens_books.csv')
book_df.head()

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

In [8]:
df = book_df[['Title', 'Description']]

In [9]:
# use find the named entities in each review
ner_analyzer = pipeline("ner",
                        model="dbmdz/bert-large-cased-finetuned-conll03-english",
                        device=device,
                        aggregation_strategy='SIMPLE')

# Look at ne's for first row
ner_analyzer(df.Description[0])

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cuda

[{'entity_group': 'MISC',
  'score': np.float32(0.9462517),
  'word': 'Where the Wild Things Are',
  'start': 0,
  'end': 25},
 {'entity_group': 'PER',
  'score': np.float32(0.9990614),
  'word': 'Max',
  'start': 34,
  'end': 37},
 {'entity_group': 'PER',
  'score': np.float32(0.9984414),
  'word': 'Max',
  'start': 175,
  'end': 178},
 {'entity_group': 'PER',
  'score': np.float32(0.9789461),
  'word': 'Sendak',
  'start': 380,
  'end': 386}]

In [10]:
list(set([entity['word'] for entity in ner_analyzer(df.Description[0]) if entity['entity_group'] == 'PER']))

['Sendak', 'Max']

In [11]:
# Generate a Series of lists of character names 
characters = df['Description'].apply(lambda x: [entity['word'] for entity in ner_analyzer(x) if entity['entity_group'] == 'PER'])
characters

0                  [Max, Max, Sendak]
1                  [##pi, Eric Carle]
2                       [Silverstein]
3           [Sam - I - Am, Dr. Seuss]
4                      [Clement Hurd]
                   ...
95                [Jon J. Muth, Muth]
96    [Shel Silverstein, Silverstein]
97       [Harry, Sirius Black, Harry]
98      [Harry, Harry, Ron, Hermione]
99                          [Galdone]
Name: Description, Length: 100, dtype: object

In [12]:
# Combine all lists into a single list, handle empty sublist (with dropna) and remove duplicates
unique_characters = (characters
                     .explode()
                     .dropna()
                     .unique()
                     .tolist())

# Filter out everything beginning with '##'...i.e subwords
unique_characters = [name for name in unique_characters if not name.startswith('##')]
len(unique_characters)

154

In [13]:
# Get a unique list of all authors
authors = list(set([author for author in book_df['Author']]))
authors

['Janette Sebring Lowrey',
 'Margaret Wise Brown',
 'Crockett Johnson',
 'Laura Joffe Numeroff',
 'Else Holmelund Minarik',
 'Peggy Parish',
 'Jean de Brunhoff',
 'Dr. Seuss',
 'Margery Williams Bianco',
 'Chris Van Allsburg',
 'Harry Allard',
 'Eric Carle',
 'Paul Galdone',
 'Munro Leaf',
 'L. Frank Baum',
 'Don Freeman',
 'H.A. Rey',
 'Janell Cannon',
 'Antoine de Saint-Exupéry',
 'P.D. Eastman',
 'Astrid Lindgren',
 'E.L. Konigsburg',
 'Mo Willems',
 'Judith Viorst',
 'C.S. Lewis',
 'David Shannon',
 'Gene Zion',
 'Beverly Cleary',
 'Jon Scieszka',
 "Madeleine L'Engle",
 'Arnold Lobel',
 'Bill Martin Jr. and John Archambault',
 'Clement Clarke Moore',
 'Jon Stone',
 'Ludwig Bemelmans',
 'Kate DiCamillo',
 'Maurice Sendak',
 'J.R.R. Tolkien',
 'Roald Dahl',
 'Lynne Reid Banks',
 'Michael Ende',
 'Kevin Henkes',
 'Robert Munsch',
 'Ezra Jack Keats',
 'A.A. Milne',
 'E.B. White',
 'Mark Twain',
 'Virginia Lee Burton',
 'Frances Hodgson Burnett',
 'Jon J. Muth',
 'Norton Juster',
 'Sam McBratney',
 'L.M. Montgomery',
 'Louis Sachar',
 'Beatrix Potter',
 'Marcus Pfister',
 'Katherine Paterson',
 'Ian Falconer',
 'Judi Barrett',
 'Arlene Mosel',
 'Watty Piper',
 'Norman Bridwell',
 'Lewis Carroll',
 'Deborah Howe',
 'Shel Silverstein',
 'Robert McCloskey',
 'Bill Martin Jr. and Eric Carle',
 'Esphyr Slobodkina',
 'J.K. Rowling',
 'Lois Lowry',
 'Doreen Cronin',
 'Laura Ingalls Wilder']

In [14]:
# Filter out all authors from list of characters
unique_characters = [name for name in unique_characters if name not in authors]
print(len(unique_characters))
unique_characters.sort()
unique_characters

145

['A',
 'A. Milne',
 'A. Rey',
 'Alexander',
 'Alice',
 'Amelia Bedelia',
 'Anne',
 'Anne Shirley',
 'Aslan',
 'Atreyu',
 'B',
 'Babar',
 'Basil E. Frankweiler',
 'Bastian',
 'Baum',
 'Becky Thatcher',
 'Bemelmans',
 'Big Bad Wolf',
 'Big Friendly Giant',
 'Big Nutbrown Hare',
 'Bilbo',
 'Bilbo Baggins',
 'Brown',
 'Bun',
 'Burton',
 'C',
 'Calvin',
 'Camilla Cream',
 'Cat in the Hat',
 'Charles Wallace',
 'Charlie',
 'Charlotte',
 'Chrysanthemum',
 'Claudia',
 'Cleary',
 'Clement Hurd',
 'Clifford',
 'Cord',
 'Corduroy',
 'Cowardly Lion',
 'De Brunhoff',
 'Despereaux',
 'Despereaux Tilling',
 'DiCamillo',
 'Dorothy',
 'Dr',
 'Eeyore',
 'Elizabeth',
 'Emily Elizabeth',
 'Falconer',
 'Ferdinand',
 'Freeman',
 'Frog',
 'Galdone',
 'Gandalf',
 'George',
 'Grinch',
 'Grover',
 'H',
 'Harold',
 'Harry',
 'Harry Potter',
 'Henkes',
 'Hermione',
 'Horton',
 'Hu',
 'Huck Finn',
 'James',
 'Jamie',
 'Jess',
 'Jess Aarons',
 'Joe Harper',
 'Jonas',
 'Keats',
 'Konigsburg',
 'Lane Smith',
 'Laura',
 'Laura Ingalls',
 'Leslie Burke',
 'Lisa',
 'Little Bear',
 'Little Nutbrown Hare',
 'Lorax',
 'Madeline',
 'Marilla',
 'Mary',
 'Mary Lennox',
 'Matilda',
 'Matthew Cuthbert',
 'Max',
 'Mayzie',
 'McGregor',
 'Meg',
 'Meg Murry',
 'Milne',
 'Milo',
 'Miss Honey',
 'Miss Nelson',
 'Muth',
 'Olivia',
 'Omri',
 'Peter',
 'Piglet',
 'Pippi',
 'Pooh',
 'Rabbit',
 'Ralph',
 'Ramon',
 'Ramona',
 'Ramona Quimby',
 'Ron',
 'S',
 'Sachar',
 'Sal',
 'Sam - I - Am',
 'Santa',
 'Santa Claus',
 'Sc',
 'Sendak',
 'Seuss',
 'Silverstein',
 'Sirius Black',
 'Sophie',
 'Stellaluna',
 'T',
 'Thing',
 'Tigger',
 'Tikki Tikki Tembo',
 'Tin Man',
 'Toad',
 'Tock',
 'Tolkien',
 'Tom',
 'Twain',
 'Viola Swamp',
 'White',
 'White Witch',
 'Wilbur',
 'Wilder',
 'Willems',
 'Willy Wonka',
 'Winnie - the',
 'Winnie - the - Pooh',
 'Wizard',
 'the G']

## Zero-Shot Classification <- Encoder/Decoder

In [16]:
books_df = pd.read_csv('../resources/Course Materials/Data/childrens_books.csv')
books_df.head()

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

In [17]:
classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli",
                      device='cuda')

Device set to use cuda

In [25]:
# List of categories ... note: I get different results if I uppercase the category names
categories = ['adventure & fantasy', 'animals & nature', 'mystery', 'humor', 'non-fiction']

classifier(books_df.Description[0], candidate_labels = categories)

{'sequence': "Where the Wild Things Are\xa0follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",
 'labels': ['adventure & fantasy',
  'animals & nature',
  'humor',
  'mystery',
  'non-fiction'],
 'scores': [0.401902437210083,
  0.3064911961555481,
  0.14998993277549744,
  0.07116298377513885,
  0.0704534500837326]}

In [26]:
# First label is the one with highest probability
books_df['Category'] = books_df['Description'].apply(lambda x: classifier(x, candidate_labels = categories)['labels'][0])
books_df[:10]

,Ranking,Title,Author,Year,Rating,Description,Category
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",adventure & fantasy
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",animals & nature
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.",non-fiction
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",humor
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.",animals & nature
5,6,Charlotte’s Web,E.B. White,1952,4.20,"Charlotte’s Web tells the story of a pig named Wilbur and his friendship with Charlotte, a clever spider who saves his life. Set on a farm, the novel explores themes of friendship, loyalty, and the cycle of life. Through Charlotte’s wise words and actions, Wilbur learns about love and sacrifice. White’s writing is filled with warmth and humor, and it’s a perfect read for both children and adults, dealing with timeless themes.",humor
6,7,"The Cat in the Hat (Cat in the Hat, #1)",Dr. Seuss,1957,4.19,"The Cat in the Hat is a landmark children’s book that tells the story of two siblings who are bored and stuck inside on a rainy day. Their day takes a wild turn when the mischievous Cat in the Hat shows up and creates chaos in their home, along with his companions, Thing 1 and Thing 2. The story’s playful rhymes and whimsical illustrations make it a fun and engaging introduction to early reading for young children.",humor
7,8,Where the Sidewalk Ends,Shel Silverstein,1974,4.34,"Where the Sidewalk Ends is a collection of poems by Shel Silverstein that blend wit, humor, and thoughtful reflections on life. With its playful rhymes and sometimes surreal themes, the book invites children to explore their imagination and the joy of language. The poems are often accompanied by Silverstein’s signature drawings, which add to the whimsical atmosphere. It’s a perfect book for children who enjoy quirky, imaginative poetry.",humor
8,9,If You Give a Mouse a Cookie,Laura Joffe Numeroff,1985,4.29,"In If You Give a Mouse a Cookie, a little mouse asks for a cookie, and from there, a series of increasingly funny and unlikely events follow. Each request leads to another, showing the mouse's insatiable appetite for things he doesn’t necessarily need. This circular story uses humor to teach children about cause and effect while entertaining them with its playful illustrations and charming narrative.",humor
9,10,Love You Forever,Robert Munsch,1986,4.38,"Love You Forever tells the heartwarming story of a mother’s enduring love for her son as he grows from a baby to an adult. Despite the passage of time and changing circumstances, the mother’s love remains constant. This book explores themes of unconditional love and the bond between parent and child, making it a perfect book for sharing at bedtime or during moments of reflection.",non-fiction

In [27]:
# Returns a Series with category counts
books_df['Category'].value_counts()

Category
humor                  42
adventure & fantasy    18
non-fiction            15
animals & nature       13
mystery                12
Name: count, dtype: int64

## Text Summarization <- Encoder/Decoder

In [30]:
summarizer = pipeline("summarization", 
                      model="facebook/bart-large-cnn", 
                      device='cuda')

Device set to use cuda

In [31]:
books_df.head()

,Ranking,Title,Author,Year,Rating,Description,Category
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",adventure & fantasy
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",animals & nature
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.",non-fiction
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",humor
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.",animals & nature

In [41]:
summary_df = pd.DataFrame({
    'title': books_df['Title'],
    'description': books_df['Description']
})
# returns a list of dictionaries
summarizer(summary_df.description[0], min_length=20, max_length=50, early_stopping=True, length_penalty=0.8)[0]['summary_text']

'Where the Wild Things Are follows Max, a young boy who imagines sailing to an island filled with wild creatures. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood.'

In [42]:
summary_df['summary'] = \
    summary_df['description'] \
        .apply(lambda x: summarizer(x, min_length=20, max_length=60, early_stopping=True, length_penalty=0.8)[0]['summary_text'])
summary_df.head()

,title,description,summary
0,Where the Wild Things Are,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.","Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood."
1,The Very Hungry Caterpillar,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.","Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis."
2,The Giving Tree,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.","Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,Green Eggs and Ham,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",Dr. Seuss’s classic story encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.
4,Goodnight Moon,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.","Goodnight Moon is a gentle, rhythmic bedtime story. The simple illustrations by Clement Hurd complement the soothing nature of the story."

## Document Similarity <- Embeddings

In [52]:
book_df.head(3)

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."

In [53]:
book_df[book_df['Title'].str.startswith('Harry Potter')]

,Ranking,Title,Author,Year,Rating,Description
13,14,"Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",J.K. Rowling,1997,4.47,"Harry Potter and the Sorcerer’s Stone introduces readers to Harry Potter, an orphan who discovers that he is a wizard and attends the magical Hogwarts School of Witchcraft and Wizardry. Along with his new friends, Harry uncovers mysteries surrounding his past and the dark wizard who killed his parents. This book starts the beloved series and sets the stage for Harry’s journey, filled with magic, adventure, and friendship."
97,98,"Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)",J.K. Rowling,1999,4.58,"Harry Potter and the Prisoner of Azkaban is the third book in the Harry Potter series, where Harry returns to Hogwarts for his third year and uncovers secrets about his past. With the arrival of the mysterious Sirius Black, Harry must navigate dark truths and face his fears. This thrilling installment explores themes of loyalty, friendship, and identity, marking a turning point in the magical world of Harry Potter."
98,99,"Harry Potter and the Chamber of Secrets (Harry Potter, #2)",J.K. Rowling,1998,4.43,"Harry Potter and the Chamber of Secrets is the second book in the Harry Potter series, where Harry returns to Hogwarts for his second year and uncovers a hidden chamber within the school. As mysterious events unfold, Harry and his friends Ron and Hermione uncover dark secrets about the school’s past. Themes of courage, friendship, and standing up for what’s right are explored in this gripping magical adventure."

In [54]:
# extract the embedding representation for each book description
feature_extractor = pipeline("feature-extraction",
                             model="sentence-transformers/all-MiniLM-L6-v2",
                             device='cuda')

Device set to use cuda

In [60]:
import numpy as np

# get the token embeddings for each book
# ... then use Mean pooling to get sentence embedding
bk_embeddings = book_df['Description'].apply(lambda x: np.mean(np.array(feature_extractor(x)[0]), axis=0))
print(type(bk_embeddings))
print(len(bk_embeddings))
print(bk_embeddings.shape)
book_embeddings = np.vstack(bk_embeddings)
book_embeddings.shape

<class 'pandas.core.series.Series'>
100
(100,)

(100, 384)

In [61]:
# get the embeddings for just the 1st Harry Potter book (idx = 13)
# Make sure output numpy array contains 1 row and as many columns as necessary
embedding_hp1 = np.array(book_embeddings[13]).reshape(1, -1)
embedding_hp1.shape

(1, 384)

In [62]:
# calculate the cosine similarity scores
from sklearn.metrics.pairwise import cosine_similarity

similarity_scores_hp1 = cosine_similarity(embedding_hp1, book_embeddings)
similarity_scores_hp1_series = pd.Series(similarity_scores_hp1.flatten(), name='similarity_score')
similarity_scores_hp1_series.head()

0    0.260106
1    0.304621
2    0.160355
3    0.194684
4    0.243536
Name: similarity_score, dtype: float64

In [63]:
# combine book titles, descriptions and scores
similarity_scores_hp1_df = pd.concat([book_df[['Title', 'Description']], similarity_scores_hp1_series], axis=1)
similarity_scores_hp1_df.head()

,Title,Description,similarity_score
0,Where the Wild Things Are,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",0.260106
1,The Very Hungry Caterpillar,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",0.304621
2,The Giving Tree,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.",0.160355
3,Green Eggs and Ham,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",0.194684
4,Goodnight Moon,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.",0.243536

In [72]:
# view the top 5 most similar books (excluding HP #1 itself)
similarity_scores_hp1_df.sort_values('similarity_score', ascending=False)[1:6]

,Title,Description,similarity_score
98,"Harry Potter and the Chamber of Secrets (Harry Potter, #2)","Harry Potter and the Chamber of Secrets is the second book in the Harry Potter series, where Harry returns to Hogwarts for his second year and uncovers a hidden chamber within the school. As mysterious events unfold, Harry and his friends Ron and Hermione uncover dark secrets about the school’s past. Themes of courage, friendship, and standing up for what’s right are explored in this gripping magical adventure.",0.639674
97,"Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)","Harry Potter and the Prisoner of Azkaban is the third book in the Harry Potter series, where Harry returns to Hogwarts for his third year and uncovers secrets about his past. With the arrival of the mysterious Sirius Black, Harry must navigate dark truths and face his fears. This thrilling installment explores themes of loyalty, friendship, and identity, marking a turning point in the magical world of Harry Potter.",0.626674
63,The Witches,"The Witches tells the story of a young boy and his grandmother who uncover a secret society of witches who despise children and plot to turn them all into mice. With the help of his grandmother, the boy must outwit the witches and save the children. The book is known for its dark humor, thrilling suspense, and memorable characters. Though it can be a bit scary, it is beloved for its unique blend of fear, adventure, and courage.",0.507633
35,"The Chronicles of Narnia (The Chronicles of Narnia, #1-7)","The Chronicles of Narnia is a series of seven fantasy novels that follow the adventures of children who stumble into the magical land of Narnia, where they meet talking animals, mythical creatures, and battle evil forces. Starting with The Lion, the Witch and the Wardrobe, the series explores themes of good versus evil, friendship, and sacrifice. The books are beloved for their imaginative world-building, allegorical elements, and moral lessons.",0.443904
55,"The Wonderful Wizard of Oz (Oz, #1)","The Wonderful Wizard of Oz is the first book in Baum's Oz series and tells the story of Dorothy, a young girl from Kansas who is swept away to the magical land of Oz. Along with her new friends—the Scarecrow, Tin Man, and Cowardly Lion—Dorothy embarks on a journey to meet the Wizard and find her way home. The book is filled with themes of friendship, courage, and the belief in oneself, and has become an iconic tale in American literature.",0.438535